### ISSUE TITLE
"EOFError: end of file reached" during manual chunking

### ISSUE THREAD

**Issue by khaledh** [Shopify/salesforce_chunker#63]
We're hitting an issue when an object is backfilled in Salesforce, causing 13M+ records to be retrieved on the next extraction (i.e. similar to a full import). The job uses manual chunking, and fails at the first step when it's querying all IDs in preparation for chunking (as opposed to querying the actual data). See the stack trace below.

From the logs it seems that the batch for fetching the IDs succeeds, but when actually fetching the CSV list of IDs, it takes about 160 seconds before failing with `EOFError: end of file reached`, which is caused by `IOError: Connection reset by peer`. It sounds like Salesforce is terminating the connection? I tried to find docs on the default request timeout when retrieving results, but couldn't find it.

The CSV response is about 340MB uncompressed, and when manually downloaded (through the Bulk Data Load Jobs UI) takes only several seconds to download. Not sure why it takes over 2.5 minutes to download via the gem.

```
06-06-2019 18:56:18 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:18 INFO  [salesforce_chunker]: GET: job/7506A00000ExpYcQAJ/batch
06-06-2019 18:56:18 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:18 INFO  [salesforce_chunker]: Waiting 10 seconds
06-06-2019 18:56:19 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847379359,"memory":{"init":1048576000,"max":10309074944,"used":963020784,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":50,"gcs_thread_count":0}}
06-06-2019 18:56:24 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847384361,"memory":{"init":1048576000,"max":10309074944,"used":963020784,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":50,"gcs_thread_count":0}}
06-06-2019 18:56:28 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:28 INFO  [salesforce_chunker]: Retrieving batch status information
06-06-2019 18:56:28 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:28 INFO  [salesforce_chunker]: GET: job/7506A00000ExpYcQAJ/batch
06-06-2019 18:56:28 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:28 INFO  [salesforce_chunker]: Batch 1 of 1: retrieving 16315058 records
06-06-2019 18:56:28 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:28 INFO  [salesforce_chunker]: GET: job/7506A00000ExpYcQAJ/batch/7516A00000GebogQAB/result
06-06-2019 18:56:29 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:56:29 INFO  [salesforce_chunker]: GET: job/7506A00000ExpYcQAJ/batch/7516A00000GebogQAB/result/7526A0000085w4X
06-06-2019 18:56:29 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847389363,"memory":{"init":1048576000,"max":10309074944,"used":972965208,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:56:34 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847394365,"memory":{"init":1048576000,"max":10309074944,"used":972965208,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:56:39 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847399366,"memory":{"init":1048576000,"max":10309074944,"used":972965208,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:56:44 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847404734,"memory":{"init":1048576000,"max":10309074944,"used":1199652480,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:56:49 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847409736,"memory":{"init":1048576000,"max":10309074944,"used":1361331424,"committed":2106064896},"gc":[{"name":"PS Scavenge","collection_count":6,"collection_time":16955},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:57:06 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847426181,"memory":{"init":1048576000,"max":10309074944,"used":304748056,"committed":2125463552},"gc":[{"name":"PS Scavenge","collection_count":7,"collection_time":30098},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:57:11 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847431190,"memory":{"init":1048576000,"max":10309074944,"used":1023766232,"committed":2125463552},"gc":[{"name":"PS Scavenge","collection_count":7,"collection_time":30098},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:57:49 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847469068,"memory":{"init":1048576000,"max":10309074944,"used":584784320,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":53,"gcs_thread_count":0}}
06-06-2019 18:57:54 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847474071,"memory":{"init":1048576000,"max":10309074944,"used":599263184,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:57:59 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847479072,"memory":{"init":1048576000,"max":10309074944,"used":599263184,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:58:04 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847484074,"memory":{"init":1048576000,"max":10309074944,"used":1049220680,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:58:09 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847489076,"memory":{"init":1048576000,"max":10309074944,"used":1972101696,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:58:14 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847494078,"memory":{"init":1048576000,"max":10309074944,"used":2501914752,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:58:19 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847499079,"memory":{"init":1048576000,"max":10309074944,"used":2501914752,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:58:24 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847504088,"memory":{"init":1048576000,"max":10309074944,"used":2696468072,"committed":3188719616},"gc":[{"name":"PS Scavenge","collection_count":8,"collection_time":64567},{"name":"PS MarkSweep","collection_count":3,"collection_time":4391}],"threads":{"count":55,"gcs_thread_count":0}}
06-06-2019 18:59:10 UTC salesforce-trident--merchants-extract INFO - {"ts":1559847550030,"memory":{"init":1048576000,"max":10309074944,"used":527648768,"committed":3818913792},"gc":[{"name":"PS Scavenge","collection_count":9,"collection_time":105005},{"name":"PS MarkSweep","collection_count":4,"collection_time":6059}],"threads":{"count":54,"gcs_thread_count":0}}
06-06-2019 18:59:10 UTC salesforce-trident--merchants-extract INFO - 2019/06/06 18:59:10 INFO  [salesforce_chunker]: end of file reached
06-06-2019 18:59:10 UTC salesforce-trident--merchants-extract INFO - ** [Bugsnag] 2019-06-06 18:59:10 +0000: Notifying https://notify.bugsnag.com of IOError
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - ** [Bugsnag] 2019-06-06 18:59:11 +0000: Notifying https://notify.bugsnag.com of IOError
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - rake aborted!
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - EOFError: end of file reached
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty/request.rb:146:in `perform'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty.rb:573:in `perform_request'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty.rb:491:in `get'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty.rb:623:in `get'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/connection.rb:47:in `get'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:104:in `retrieve_raw_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/manual_chunking_breakpoint_query.rb:16:in `block in get_batch_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/manual_chunking_breakpoint_query.rb:15:in `get_batch_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:39:in `block in download_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:34:in `block in download_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:31:in `download_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/manual_chunking_query.rb:19:in `initialize'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker.rb:43:in `query'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractors/salesforce/salesforce_bulk.rb:25:in `extract'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:662:in `block in extract_pipeline'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `block in measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:53:in `duration'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:661:in `extract_pipeline'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:817:in `block in run'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `block in measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:53:in `duration'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:814:in `run'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat.rb:226:in `run'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/Rakefile:115:in `block in <main>'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<main>'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /usr/bin/bundle:23:in `<main>'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - 
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - Caused by:
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - IOError: Connection reset by peer
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - org/jruby/ext/openssl/SSLSocket.java:836:in `sysread_nonblock'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/jruby-openssl-0.9.21-java/lib/jopenssl23/openssl/buffering.rb:177:in `read_nonblock'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty/request.rb:146:in `perform'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty.rb:573:in `perform_request'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty.rb:491:in `get'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/httparty-0.16.4/lib/httparty.rb:623:in `get'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/connection.rb:47:in `get'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:104:in `retrieve_raw_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/manual_chunking_breakpoint_query.rb:16:in `block in get_batch_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/manual_chunking_breakpoint_query.rb:15:in `get_batch_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:39:in `block in download_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:34:in `block in download_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/job.rb:31:in `download_results'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker/manual_chunking_query.rb:19:in `initialize'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/vendor/cache/salesforce_chunker-4698c6ec519d/lib/salesforce_chunker.rb:43:in `query'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractors/salesforce/salesforce_bulk.rb:25:in `extract'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:662:in `block in extract_pipeline'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `block in measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:53:in `duration'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:661:in `extract_pipeline'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:817:in `block in run'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `block in measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:53:in `duration'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/statsd-instrument-2.1.0/lib/statsd/instrument.rb:284:in `measure'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat/extractor.rb:814:in `run'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/lib/longboat.rb:226:in `run'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /app/Rakefile:115:in `block in <main>'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /artifacts/jruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<main>'
06-06-2019 18:59:11 UTC salesforce-trident--merchants-extract INFO - /usr/bin/bundle:23:in `<main>'
```

**Comment by khaledh** [comment]
@csholmes Is this related to #50? Any idea how to proceed?

**Comment by csholmes** [comment]
I suspect this is either a JRuby or a Salesforce issue. I'm having trouble reproducing the issue though, except for once actually I caught the same issue with PK Chunking trying to download a very large batch.

It doesn't seem to take that long "normally", when there isn't an issue. It takes less than a minute to download and decompress.

To attempt to solve this issue, I added `IOError` to the retry handler: https://github.com/Shopify/salesforce_chunker/pull/69

**Comment by khaledh** [comment]
@csholmes OK, thanks. We switched to PK chunking a while ago to avoid hitting this issue. We currently have one job that uses manual chunking, and the total data size is in the range of 150K, so most probably it's not going to be impacted. But thanks for adding the retry for `IOError`, just in case.
